---
title: "Cost stability"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE, warning = FALSE}
#PACKAGES
library(tidyverse)

##DATA
load("../data/costs.rda")
```

## SCM dataset
```{r, fig.align="center", fig.width=10, fig.height=8}
tests <- seq(50, 1000, 50)
p <- data %>%
  setNames(tests) %>%
  add_column(rep = 1:nrow(.), .before = 1) %>%
  gather(nrOfMultiplets, Cost, -rep) %>%
  mutate(nrOfMultiplets = as.numeric(nrOfMultiplets)) %>%
  ggplot() +
  geom_boxplot(aes(nrOfMultiplets, Cost, group = nrOfMultiplets)) +
  theme_bw() +
  labs(
    x = "Number of synthetic multiplets",
    caption = "50 replicates per number of synthetic multiplets"
  ) + 
  theme(plot.caption = element_text(hjust = 0)) +
  scale_x_continuous(breaks = tests, minor_breaks = tests)

p

ggsave(
  plot = p, filename = '../figures/figure1.pdf',
  device = cairo_pdf, height = 180,
  width = 240, units = "mm"
)
```

## Small intestine dataset

```{r, fig.align="center", fig.width=10, fig.height=8}
load('../data/costs2.rda')
nSyntheticMultiplets <- c(10, 50, 100, 500, 1000, 5000, 10000)
tibble(
  nSyntheticMultiplets = nSyntheticMultiplets,
  costs
) %>%
  unnest() %>%
  ggplot() +
  geom_boxplot(aes(nSyntheticMultiplets, costs, group = nSyntheticMultiplets)) +
  theme_bw() +
  theme(
    plot.caption = element_text(hjust = 0),
    axis.text.x = element_text(angle = 90, hjust = 0.5)
  ) +
  scale_x_log10(breaks = nSyntheticMultiplets, minor_breaks = nSyntheticMultiplets) +
  labs(
    x = "Number of synthetic multiplets", y = "Cost",
    caption = "40 replicates per number of synthetic multiplets"
  )
```

```{r}
sessionInfo()
```

