---
title: "sortedMultiplets20171116-distToSlice"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, echo = FALSE}
packages <- c(
    "sp.scRNAseq",
    "sp.scRNAseqTesting",
    "sp.scRNAseqData",
    "printr",
    "ggthemes",
    "tidyverse"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)
```

Run method.
```{r}
sng <- str_detect(colnames(countsSorted2), "^s")

#create counts objects
cObjSng <- spCounts(countsSorted2[, sng], countsSortedERCC2[, sng])
cObjMul <- spCounts(countsSorted2[, !sng], countsSortedERCC2[, !sng])

#spUnsupervised
uObj <- spUnsupervised(cObjSng)

#rename classes
positions <- str_extract(colnames(getData(cObjSng, "counts")), "...$")
newClass <- case_when(
  positions == "E03" ~ "A375", #what is this? sorting issue?
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("01", "02", "03", "04")) ~ "HOS",
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("05", "06", "07", "08")) ~ "HCT116",
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("09", "10", "11", "12")) ~ "A375",
  TRUE ~ "error"
)
corresp <- getData(uObj, "classification") %>%
  tibble(oldClass = ., newClass = newClass) %>%
  distinct()

classification(uObj) <- newClass

gm <- getData(uObj, "groupMeans")
colnames(gm) <- pull(corresp, newClass)[match(colnames(gm), pull(corresp, oldClass))]
groupMeans(uObj) <- gm

tm <- getData(uObj, "tsneMeans")
tm$classification <- pull(corresp, newClass)[match(tm$classification, pull(corresp, oldClass))]
tsneMeans(uObj) <- tm

#spSwarm
sObj_distToSlice <- spSwarm(cObjMul, uObj, distFun = "distToSlice", swarmsize = 50, maxiter = 10)
sObj_bic <- spSwarm(cObjMul, uObj, distFun = "bic", swarmsize = 50, maxiter = 10)
#sObj_distToSliceNorm <- spSwarm(cObjMul, uObj, distFun = "distToSliceNorm", swarmsize = 50, maxiter = 10)
#sObj_distToSliceTop <- spSwarm(cObjMul, uObj, distFun = "distToSliceTop", swarmsize = 50, maxiter = 10, cells = 4)
#sObj_distToSliceEuclid <- spSwarm(cObjMul, uObj, distFun = "distToSliceEuclid", swarmsize = 50, maxiter = 10)
#sObj_distToSlicePearson <- spSwarm(cObjMul, uObj, distFun = "distToSlicePearson", swarmsize = 50, maxiter = 10)
```

Evaluate the information still contained in the permuted data. Do this by randomly selecting 5000 genes from the matrix and running pca

```{r}
.makeSyntheticSlice.vec <- function(
  cellTypes,
  fractions
){
  #reformat variables to facilitate vectorized calculations
  fractions.vec <- as.vector(t(fractions))
  
  sVec <- sort(rep(1:nrow(fractions), length(c(cellTypes)) / nrow(fractions)))
  sepMats <- split(t(cellTypes), sVec)
  lSepMats <- lapply(sepMats, function(x) t(matrix(x, ncol = ncol(cellTypes))))
  cellTypes.vec <- do.call(rbind, lSepMats)
  
  #perform multiplication calculation
  multiply <- fractions.vec * cellTypes.vec
  
  #reformat for vectorized sum calculation
  list <- split(c(t(multiply)), sVec)
  flist <- lapply(list, function(x) matrix(x, ncol = ncol(cellTypes)))
  mat <- do.call(rbind, flist)
  
  #perform sum calculation
  sums <- rowSums(mat)
  
  #reformat for subsequent vectorized calculations with output
  matrix(sums, ncol = nrow(fractions))
}

distToSlice.vec <- function(
  fractions,
  cellTypes,
  oneMultiplet,
  .makeSyntheticSlice.vec = .makeSyntheticSlice.vec,
  ...
) {
  
  #normalize
  fractions <- fractions / rowSums(fractions)
  
  #makeSyntheticSlice
  a <- .makeSyntheticSlice.vec(cellTypes, fractions)
  
  #distToSlice
  oneMultiplet.vec <- matrix(
    rep(oneMultiplet, ncol(a)),
    ncol = ncol(a)
  )
  colSums(abs(a - oneMultiplet.vec))
}

bic.vec <- function(
  fractions,
  cellTypes,
  oneMultiplet,
  .makeSyntheticSlice.vec = .makeSyntheticSlice.vec
  ...
){
  #normalize
  fractions <- fractions / rowSums(fractions)
  
  #makeSyntheticSlice
  a <- .makeSyntheticSlice.vec(cellTypes, fractions)
  
  #bic
  oneMultiplet.vec <- matrix(
    rep(oneMultiplet, ncol(a)),
    ncol = ncol(a)
  )
  n <- nrow(fractions)
  e <- colSums(abs(a - oneMultiplet.vec)^2) * 1/n
  
  k <- apply(fractions, 1, function(x) length(which(x > 0)))
  
  (n * log(e)) + (k * log(n))
}
```

Use class means, calculated from the permuted counts matrix, to calculate the 
```{r, fig.align='center', fig.height=8, fig.width=10}

#calculate costs
cost_distToSlice <- permutationCosts(
  groupMeanPermutations,
  cObjMul,
  uObj,
  sObj_distToSlice,
  100,
  distFun = sp.scRNAseq:::distToSlice
)

cost_bic <- permutationCosts(
  groupMeanPermutations,
  cObjMul,
  uObj,
  sObj_bic,
  100,
  distFun = sp.scRNAseq:::bic
)

# cost_distToSliceNorm <- permutationCosts(
#   groupMeanPermutations,
#   cObjMul, 
#   uObj,
#   sObj_distToSliceNorm,
#   100,
#   distFun = sp.scRNAseq:::distToSliceNorm
# )

#cost_distToSliceTop <- permutationCosts(
#  groupMeanPermutations,
#  cObjMul, 
#  uObj, 
#  sObj_distToSliceTop, 
#  100, 
#  distFun = sp.scRNAseq:::distToSliceTop
#)

# cost_distToSliceEuclid <- permutationCosts(
#   groupMeanPermutations,
#   cObjMul, 
#   uObj, 
#   sObj_distToSliceEuclid,
#   100,
#   distFun = sp.scRNAseq:::distToSliceEuclid
# )

# cost_distToSlicePearson <- permutationCosts(
#   groupMeanPermutations,
#   cObjMul,
#   uObj,
#   sObj_distToSlicePearson,
#   100,
#   distFun = sp.scRNAseq:::distToSlicePearson
# )

save(
  sObj_distToSlice,
  sObj_bic, 
  cost_distToSlice,
  cost_bic,
  file = "~/Desktop/data.rda",
  compress = "bzip2"
)
```

Plot results for distToSlice.
```{r, fig.align='center', fig.height=8, fig.width=10}
plotDistPermutations(cost_distToSlice)
```

Plot results for bic.
```{r, fig.align='center', fig.height=8, fig.width=10}
plotDistPermutations(cost_bic, bw = 1)
```

```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSliceNorm.
plotDistPermutations(cost_distToSliceNorm)
```

```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSliceTop.
#plotDistPermutations(cost_distToSliceTop)
```

```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSliceEuclid.
plotDistPermutations(cost_distToSliceEuclid)
```


```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSlicePearson.
plotDistPermutations(cost_distToSlicePearson)
```


###Plot for individual multiplets

Plot results for distToSlice.
```{r, fig.align='center', fig.height=8, fig.width=10}
plotDistPermutations(cost_distToSlice, facet = TRUE)
```


Plot results for bic.
```{r, fig.align='center', fig.height=8, fig.width=10}
plotDistPermutations(cost_bic, bw = 1, facet = TRUE)
```

```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSliceNorm.
plotDistPermutations(cost_distToSliceNorm, TRUE)
```


```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSliceTop.
plotDistPermutations(cost_distToSliceTop, TRUE)
```

```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSliceEuclid.
plotDistPermutations(cost_distToSliceEuclid, TRUE)
```

```{r, fig.align='center', fig.height=8, fig.width=10, eval = FALSE, echo = FALSE}
#Plot results for distToSlicePearson.
plotDistPermutations(cost_distToSlicePearson, TRUE)
```

