---
title: "Testing new swarm algo"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
#PACKAGES
packages <- c(
    "sp.scRNAseq",
    "sp.scRNAseqData",
    "sp.scRNAseqTesting",
    "printr",
    "ggthemes",
    "tidyverse"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

##DATA
s <- grepl("^s", colnames(countsSorted2))
cObjSng <- spCounts(countsSorted2[,s], countsSortedERCC2[,s])
cObjMul <- spCounts(countsSorted2[,!s], countsSortedERCC2[,!s])
uObj <- spUnsupervised(cObjSng)

#rename classes
positions <- str_extract(colnames(getData(cObjSng, "counts")), "...$")
newClass <- case_when(
  positions == "E03" ~ "A375", #what is this? sorting issue?
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("01", "02", "03", "04")) ~ "HOS",
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("05", "06", "07", "08")) ~ "HCT116",
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("09", "10", "11", "12")) ~ "A375",
  TRUE ~ "error"
)
corresp <- getData(uObj, "classification") %>%
  tibble(oldClass = ., newClass = newClass) %>%
  distinct()

classification(uObj) <- newClass

gm <- getData(uObj, "groupMeans")
colnames(gm) <- pull(corresp, newClass)[match(colnames(gm), pull(corresp, oldClass))]
groupMeans(uObj) <- gm

tm <- getData(uObj, "tsneMeans")
tm$classification <- pull(corresp, newClass)[match(tm$classification, pull(corresp, oldClass))]
tsneMeans(uObj) <- tm
```

```{r, eval = FALSE}
#TEST
sObj <- spSwarm(cObjSng, cObjMul, uObj, maxiter = 10, swarmsize = 150, nSyntheticMultiplets = 200, cores = 3)
save(sObj, file = "~/Github/sp.scRNAseqTesting/inst/testingPoissonAlgo/newAlgoSpSwarm.rda")
```

```{r, echo = FALSE}
load("~/Github/sp.scRNAseqTesting/inst/testingPoissonAlgo/newAlgoSpSwarm.rda")
```

### Show average stats for multiplets dependant on the number of cell in the multiplet.
```{r}
known <- setupPlate(countsSortedMeta2)
res <- checkResults(sObj, known, 0)

res %>%
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  mutate(cellsInMultiplet = str_count(cellTypes, "-") + 1) %>%
  group_by(cellsInMultiplet) %>%
  summarize(
    meanTPR = mean(TPR, na.rm = TRUE),
    meanTNR = mean(TNR, na.rm = TRUE),
    meanACC = mean(ACC, na.rm = TRUE)
  )
```

### Show average stats for multiplets dependant on the combination of cells in the multiplet.
```{r}
res %>%
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  mutate(cellsInMultiplet = str_count(cellTypes, "-") + 1) %>%
  group_by(cellTypes) %>%
  summarize(
    meanTPR = mean(TPR, na.rm = TRUE),
    meanTNR = mean(TNR, na.rm = TRUE),
    meanACC = mean(ACC, na.rm = TRUE)
  )
```

### Print all stats.
```{r}
print <- res %>% 
  mutate(connections.detected = map_chr(data.detected, function(x) paste(unlist(x), collapse = ", "))) %>%
  mutate(connections.expected = map_chr(data.expected, function(x) paste(unlist(x), collapse = ", "))) %>%
  select(-(data.detected:data.expected)) %>%
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  select(-(plate:cellNumber)) %>%
  rename(cellsSorted = cellTypes) %>%
  inner_join(matrix_to_tibble(getData(sObj, "spSwarm"), "multiplet"), by = "multiplet") %>%
  mutate(HOS = round(HOS, digits = 2), HCT116 = round(HCT116, digits = 2), A375 = round(A375, digits = 2)) %>%
  unite(fractions, HOS, HCT116, A375, sep = ", ") %>%
  rename("fractions (HOS, HCT116, A375)" = fractions) %>%
  select(multiplet, cellsSorted, connections.expected, connections.detected, `fractions (HOS, HCT116, A375)`, tp:ACC)

as.data.frame(print)
```



