---
title: "Deconvolution of mouse small intestine and colon multiplets"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
packages <- c(
  "sp.scRNAseq", "sp.scRNAseqData", "sp.scRNAseqTesting", "printr",
  "ggthemes", "tidyverse", "viridis"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)
```

```{r, warning=FALSE}
##DATA
s <- str_detect(colnames(countsMgfp), "^s")
commonGenes <- intersect(rownames(countsMgfp), rownames(countsRegev))

sng <- cbind(countsMgfp[commonGenes, s], countsRegev[commonGenes, ])
mul <- countsMgfp[commonGenes, !s]

erccSng <- cbind(
  countsMgfpERCC[, s], 
  matrix(NA, nrow = nrow(countsMgfpERCC), ncol = ncol(countsRegev))
)
erccMul <- cbind(countsMgfpERCC[, !s])

#setup spCounts
cObjSng <- spCounts(sng, erccSng)
cObjMul <- spCounts(mul, erccMul)

#load spUnsupervised and spSwarm
load('../data/uObj.rda')
load('../data/sObj.rda')
```

```{r, fig.align="center", fig.height=8, fig.width=10}
plotUnsupervisedClass(uObj, cObjSng)
```

```{r}
#cluster to get class order
hc <- hclust(as.dist(1 - cor(getData(sObj, "spSwarm"), method = "pearson")))
cOrder <- hc[[4]][hc[[3]]]

#cluster to get sample order
hs <- hclust(as.dist(1 - cor(t(getData(sObj, "spSwarm")), method = "pearson")))
sOrder <- hs[[4]][hs[[3]]]
```

```{r, fig.align="center", fig.height=8, fig.width=10}
p <- getData(sObj, "spSwarm") %>%
  rownames_to_column("sample") %>%
  as_tibble() %>%
  gather(class, fraction, -sample) %>%
  inner_join(countsMgfpMeta, by = "sample") %>%
  mutate(
    sample = parse_factor(sample, levels = sOrder),
    class = parse_factor(class, levels = cOrder)
  ) %>%
  mutate(classTissue = case_when(
    str_detect(class, "^C") ~ "Colon",
    str_detect(class, "^SI") ~ "Small Intestine",
    TRUE ~ "Miscellaneous"
  )) %>%
  ggplot() +
  geom_tile(aes(class, sample, fill = fraction)) +
  facet_grid(tissue ~ classTissue, scales = "free") +
  scale_fill_viridis() +
  theme_bw() +
  labs(x = "Samples") +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(),
    legend.position = "top"
  ) +
  guides(fill = guide_colourbar(title = "Fraction", title.position = "top", title.hjust = 0.5))

p

#ggsave(
#  plot = p,
#  filename = '../figures/figure.pdf',
#  device = cairo_pdf,
#  height = 180,
#  width = 240,
#  units = "mm"
#)
```


