---
title: "sortedMultiplets20171116-distToSliceEuclid"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r}
packages <- c(
    "sp.scRNAseq",
    "sp.scRNAseqData",
    "sp.scRNAseqTesting",
    "printr",
    "ggthemes",
    "tidyverse"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)
```

Run method.
```{r, fig.align='center', fig.height=8, fig.width=10}
sng <- str_detect(colnames(countsSorted2), "^s")

#create counts objects
cObjSng <- spCounts(countsSorted2[, sng], countsSortedERCC2[, sng])
cObjMul <- spCounts(countsSorted2[, !sng], countsSortedERCC2[, !sng])

#plot
plotCounts(cObjSng, cObjMul, type = "ercc")

#spUnsupervised
uObj <- spUnsupervised(cObjSng)

#rename classes
positions <- str_extract(colnames(getData(cObjSng, "counts")), "...$")
newClass <- case_when(
  positions == "E03" ~ "A375", #what is this? sorting issue?
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("01", "02", "03", "04")) ~ "HOS",
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("05", "06", "07", "08")) ~ "HCT116",
  positions %in% paste0(sort(rep(LETTERS[1:8], 4)), c("09", "10", "11", "12")) ~ "A375",
  TRUE ~ "error"
)
corresp <- getData(uObj, "classification") %>%
  tibble(oldClass = ., newClass = newClass) %>%
  distinct()

classification(uObj) <- newClass

gm <- getData(uObj, "groupMeans")
colnames(gm) <- pull(corresp, newClass)[match(colnames(gm), pull(corresp, oldClass))]
groupMeans(uObj) <- gm

tm <- getData(uObj, "tsneMeans")
tm$classification <- pull(corresp, newClass)[match(tm$classification, pull(corresp, oldClass))]
tsneMeans(uObj) <- tm

#plot
plotUnsupervised(uObj)

#spSwarm
sObj <- spSwarm(cObjMul, uObj, distFun = "distToSliceEuclid", swarmsize = 50, maxiter = 10)
plotSwarm(sObj, uObj, cObjSng, cObjMul, type = "heat")
print(paste("sum of optimization costs: ", sum(getData(sObj, "costs"))))
```

Plot costs.
```{r, fig.align='center', fig.height=8, fig.width=10}
getData(sObj, "costs") %>%
  as_tibble() %>%
  ggplot() +
  geom_histogram(aes(x = value), binwidth = 5000000) +
  theme_few()
```

Setup known multiplet compositions.
```{r}
#setup information
#order everything by column
multiplets <- c(
  c(rep("A375-HCT116", 3), rep("HCT116-HOS", 2), rep("A375-HOS", 3)),
  c(rep("A375-HCT116", 3), rep("HCT116-HOS", 2), rep("A375-HOS", 3)),
  c(rep("A375-HCT116", 2), rep("HCT116-HOS", 3), rep("A375-HOS", 3)),
  c(rep("A375-HCT116", 2), rep("HCT116-HOS", 3), rep("A375-HOS", 3)),
  c(rep("A375-HCT116-HOS", 3), rep("HCT116-HCT116-HOS", 2), rep("A375-HOS-HOS", 3)),
  c(rep("A375-HCT116-HOS", 3), rep("HCT116-HCT116-HOS", 2), rep("A375-HOS-HOS", 3)),
  c(rep("A375-HCT116-HOS", 2), rep("HCT116-HCT116-HOS", 3), rep("A375-HOS-HOS", 3)),
  c(rep("A375-HCT116-HOS", 2), rep("HCT116-HCT116-HOS", 3), rep("A375-HOS-HOS", 3)),
  c(rep("A375-HOS-HOS-HOS", 3), rep("A375-A375-HCT116-HCT116", 2), rep("A375-A375-HCT116-HOS", 3)),
  c(rep("A375-HOS-HOS-HOS", 3), rep("A375-A375-HCT116-HCT116", 2), rep("A375-A375-HCT116-HOS", 3)),
  c(rep("A375-HOS-HOS-HOS", 2), rep("A375-A375-HCT116-HCT116", 3), rep("A375-A375-HCT116-HOS", 3)),
  c(rep("A375-HOS-HOS-HOS", 2), rep("A375-A375-HCT116-HCT116", 3), rep("A375-A375-HCT116-HOS", 3))
)

cols <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
rows <- LETTERS[1:8]
names <- paste0("m.NJB00204.", rep(rows, 12), sort(rep(cols, 8)))

#make plate data
plateData <- tibble(
  row = rep(rows, 12),
  column = sort(rep(cols, 8)),
  multipletName = names,
  multipletComposition = multiplets
) %>%
mutate(connections = str_split(multipletComposition, "-")) %>%
mutate(connections = {map(.$connections, combn, 2)})

viewAsPlate(plateData)
```

Evaluate correlation between expected and detected results.

note:  
tp = true positives  
tn = true negatives  
fp = false positives  
fn = false negatives  
TPR = true positive rate / sensitivity = tp / (tp + fn)  
TNR = true negative rate / specificity = tn / (tn + fp)  
ACC = accuracy = (tp + tn) / (tp + tn + fp + fn)  

```{r}
#subset plateData to include only multiplets in the results
plateData <- filter(plateData, multipletName %in% colnames(getData(cObjMul, "counts")))
known <- setupPlate(plateData)
res <- checkResults(sObj, known, 0.2) %>%
  mutate(cellsInWell = case_when(
    str_extract(multiplet, "..$") %in% c("01", "02", "03", "04") ~ 2L,
    str_extract(multiplet, "..$") %in% c("05", "06", "07", "08") ~ 3L,
    str_extract(multiplet, "..$") %in% c("09", "10", "11", "12") ~ 4L
  )) %>%
  select(multiplet, cellsInWell, data.detected:ACC)

res %>%
  summarize(
    meanTPR = mean(TPR, na.rm = TRUE),
    meanTNR = mean(TNR, na.rm = TRUE),
    meanACC = mean(ACC, na.rm = TRUE)
  )
```

Visualize results in plate.
```{r, fig.align='center', fig.height=8, fig.width=10}
#visualize false positive and false negative results
resultsInPlate(res, plateData, "fp")
resultsInPlate(res, plateData, "fn")
resultsInPlate(res, plateData, "tp")
resultsInPlate(res, plateData, "tn")
resultsInPlate(res, plateData, "TNR")
resultsInPlate(res, plateData, "TPR")
resultsInPlate(res, plateData, "ACC")
```

Show all results.
```{r}
res %>%
  printResults(., TRUE, sObj)
```
