---
title: "Permutation analysis mouse data"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
packages <- c(
  "CIMseq", "sp.scRNAseqData", "printr", "ggthemes", "tidyverse", 
  "viridis"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)
```

0 = A375
1 = HCT116
2 = HOS

renameClasses <- function(class) {
  case_when(
    class == "0" ~ "A375",
    class == "1" ~ "HCT116",
    class == "2" ~ "HOS",
    TRUE ~ "error"
  )
}

getData(cObjSng, "classification") <- renameClasses(getData(cObjSng, "classification"))
fractions <- getData(sObj, "fractions")
colnames(fractions) <- renameClasses(colnames(fractions))
sObj@fractions <- fractions
```{r}
#expected connections with SCM dataset
#A375-A375 = 22   
#A375-HCT116 = 84
#A375-HOS = 100
#HCT116-HCT116 = 20
#HCT116-HOS = 52
#HOS-HOS = 42

#FUNCTIONS
calculateConnectionScore <- function(sObj, samples = NULL, cut = 0) {
  swarm <- getData(sObj, "fractions")
  
  if(is.null(samples)) {
    samples <- rownames(swarm)
  }
  
  swarm <- as.data.frame(t(swarm[samples, ]), stringsAsFactors = FALSE)
  costs <- getData(sObj, "costs")
  names(costs) <- rownames(getData(sObj, "fractions"))
  #combos <- as.data.frame(combn(rownames(swarm), 2), stringsAsFactors = FALSE)
  combos <- as.data.frame(
    t(expand.grid(rownames(swarm), rownames(swarm), stringsAsFactors = FALSE)),
    stringsAsFactors = FALSE
  )
  scores <- map_dbl(combos, function(x) {
    adjust <- if_else(identical(x[1], x[2]), 0.5, 1)
    b <- apply(swarm[c(x[1], x[2]), ], 2, function(r) all(r > cut))
    c <- costs[names(b)[b]]
    (sum(swarm[x, names(b)[b]]) * adjust) - sum(swarm[x, ]) / sum(swarm) #/ sum(c)
  })
  as.data.frame(t(combos), stringsAsFactors = FALSE) %>%
    as_tibble() %>%
    rename(from = Var1, to = Var2) %>%
    add_column(score = scores)
}

##DATA
s <- str_detect(colnames(countsMgfp), "^s")
commonGenes <- intersect(rownames(countsMgfp), rownames(countsRegev))

sng <- cbind(countsMgfp[commonGenes, s], countsRegev[commonGenes, ])
mul <- countsMgfp[commonGenes, !s]

erccSng <- cbind(
  countsMgfpERCC[, s], 
  matrix(NA, nrow = nrow(countsMgfpERCC), ncol = ncol(countsRegev))
)
erccMul <- cbind(countsMgfpERCC[, !s])

#setup spCounts
cObjSng <- spCounts(sng, erccSng)
#cObjMul <- spCounts(mul, erccMul)

testSamples <- c(
  "m.NJA00107.G09", "m.NJA00107.D12", "m.NJA00107.A02",
  "m.NJA00107.A10", "m.NJA00107.C08"
)
cObjMul <- spCounts(mul[, testSamples], erccMul[, testSamples])

load('../../testingPoissonMouse/data/uObj.rda')
load('../../testingPoissonMouse/data/sObj.rda')
load('../data/permutations.rda')
```

```{r, fig.align="center", fig.width = 10, fig.height=8}
map(perms, getData, "costs") %>%
  map(as_tibble) %>%
  reduce(bind_cols) %>%
  setNames(1:length(perms)) %>%
  add_column(real = getData(sObj, "costs")[rownames(getData(sObj, "spSwarm")) %in% testSamples]) %>%
  add_column(sample = rownames(getData(sObj, "spSwarm"))[rownames(getData(sObj, "spSwarm")) %in% testSamples]) %>%
  gather(type, cost, -sample) %>%
  mutate(permutation = if_else(type == "real", "NA", type)) %>%
  mutate(type = if_else(type == "real", "real", "permuted")) %>%
  ggplot() +
  geom_point(aes(sample, cost, colour = type))
```

```{r, fig.align="center", fig.width = 10, fig.height=8}
map_dfr(perms, getData, "spSwarm") %>%
  as.matrix() %>%
  heatmap()
```

```{r}
permScores <- map_dfr(perms, calculateConnectionScore, .id = "permutation") %>%
  add_column(type = "permuted")
realScores <- calculateConnectionScore(sObj, samples = testSamples) %>%
  add_column(permutation = NA, type = "real")
```

```{r, fig.align="center", fig.width = 10, fig.height=8}
bind_rows(permScores, realScores) %>%
  unite(connection, from, to, sep = "-") %>%
  ggplot() +
  geom_point(aes(connection, score, colour = type)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
realScores %>%
  mutate(permScore = map2(from, to, function(x, y) {
    filter(permScores, from == x, to == y)$score
  })) %>%
  mutate(p.value = map2_dbl(score, permScore, function(r, p) {
    if_else(
      sum(p >= r) / length(p) == 0,
      10^-log10(length(p)),
      sum(p >= r) / length(p)
    )
  })) %>%
  select(-permutation, -type, -permScore)
```

```{r}
sessionInfo()
```

