---
title: "Permutation analysis mouse data"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
packages <- c(
  "sp.scRNAseq", "sp.scRNAseqData", "printr", "ggthemes", "tidyverse", 
  "viridis"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)
```

```{r}
#FUNCTIONS
calculateConnectionScore <- function(sObj, samples = NULL) {
  swarm <- getData(sObj, "spSwarm")
  
  if(is.null(samples)) {
    samples <- rownames(swarm)
  }
  
  swarm <- as.data.frame(t(swarm[samples, ]), stringsAsFactors = FALSE)
  costs <- getData(sObj, "costs")
  combos <- as.data.frame(combn(rownames(swarm), 2), stringsAsFactors = FALSE)
  prod <- map(combos, function(x) {
    swarm[x[1], ] * swarm[x[2], ]
  })
  byCost <- map(prod, function(x) x / costs)
  scores <- map_dbl(byCost, sum)
  as.data.frame(t(combos), stringsAsFactors = FALSE) %>%
    as_tibble() %>%
    rename(from = V1, to = V2) %>%
    add_column(score = scores)
}

##DATA
s <- str_detect(colnames(countsMgfp), "^s")
commonGenes <- intersect(rownames(countsMgfp), rownames(countsRegev))

sng <- cbind(countsMgfp[commonGenes, s], countsRegev[commonGenes, ])
mul <- countsMgfp[commonGenes, !s]

erccSng <- cbind(
  countsMgfpERCC[, s], 
  matrix(NA, nrow = nrow(countsMgfpERCC), ncol = ncol(countsRegev))
)
erccMul <- cbind(countsMgfpERCC[, !s])

#setup spCounts
cObjSng <- spCounts(sng, erccSng)
#cObjMul <- spCounts(mul, erccMul)

testSamples <- c(
  "m.NJA00107.G09", "m.NJA00107.D12", "m.NJA00107.A02",
  "m.NJA00107.A10", "m.NJA00107.C08"
)
cObjMul <- spCounts(mul[, testSamples], erccMul[, testSamples])

load('../testingPoissonMouse/data/uObj.rda')
load('../testingPoissonMouse/data/sObj.rda')
load('data/permutations.rda')
```

```{r}
map(perms, getData, "costs") %>%
  map(as_tibble) %>%
  reduce(bind_cols) %>%
  setNames(1:length(perms)) %>%
  add_column(real = getData(sObj, "costs")[rownames(getData(sObj, "spSwarm")) %in% testSamples]) %>%
  add_column(sample = rownames(getData(sObj, "spSwarm"))[rownames(getData(sObj, "spSwarm")) %in% testSamples]) %>%
  gather(type, cost, -sample) %>%
  mutate(permutation = if_else(type == "real", "NA", type)) %>%
  mutate(type = if_else(type == "real", "real", "permuted")) %>%
  ggplot() +
  geom_point(aes(sample, cost, colour = type))
```


```{r}
permScores <- map_dfr(perms, calculateConnectionScore, .id = "permutation")
realScores <- calculateConnectionScore(sObj, samples = testSamples)
```

