---
title: "Mouse analysis"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
packages <- c(
  "sp.scRNAseq", "sp.scRNAseqData", "seqTools", "printr",
  "ggthemes", "tidyverse"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

##DATA
load('../data/uObjs.rda')
```

```{r, warning=FALSE}
s <- str_detect(colnames(countsMgfp), "^s")
commonGenes <- intersect(rownames(countsMgfp), rownames(countsRegev))

sng <- cbind(countsMgfp[commonGenes, s], countsRegev[commonGenes, ])
mul <- countsMgfp[commonGenes, !s]

erccSng <- cbind(
  countsMgfpERCC[, s], 
  matrix(NA, nrow = nrow(countsMgfpERCC), ncol = ncol(countsRegev))
)
erccMul <- cbind(countsMgfpERCC[, !s])

boolMulC <- colnames(mul) %in% filter(countsMgfpMeta, tissue == "colon")$sample
boolSngC <- colnames(sng) %in% filter(countsMgfpMeta, tissue == "colon")$sample

#setup spCounts
cObjSng <- spCounts(sng, erccSng)
cObjMul <- spCounts(mul, erccMul)

cObjSngSi <- spCounts(sng[, !boolSngC], erccSng[, !boolSngC])
cObjSngC <- spCounts(sng[, boolSngC], erccSng[, boolSngC])

cObjMulSi <- spCounts(mul[, !boolMulC], erccMul[, !boolMulC])
cObjMulC <- spCounts(mul[, boolMulC], erccMul[, boolMulC])
```

## Colon
```{r, fig.align="center", fig.width=10, fig.height=8}
plotUnsupervisedClass(uObjC, cObjSngC)
plotUnsupervisedMarkers(uObjC, cObjSngC, c("Lgr5", "Muc2", "Ptprc", "Chga", "Slc40a1"))
plotUnsupervisedMarkers(uObjC, cObjSngC, c("Mki67"))
```

```{r, fig.align="center", fig.width=10, fig.height=8, eval = FALSE, echo = FALSE}
plotUnsupervisedClass(uObjC, cObjSngC) %>% 
  plotData() %>% 
  inner_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  count(plate, Classification) %>%
  spread(plate, n, fill = 0) %>%
  gather(plate, n, -Classification) %>%
  group_by(plate) %>% 
  mutate(percent = 100 * (n / sum(n))) %>%
  mutate(supervisedClass = case_when(
    Classification == "A1" ~ "Stem",
    Classification == "B1" ~ "Stem",
    Classification == "C1" ~ "TA cells",
    Classification == "D1" ~ "Colonocytes",
    Classification == "E1" ~ "Goblet",
    Classification == "F1" ~ "Goblet",
    Classification == "G1" ~ "TA cells",
    Classification == "H1" ~ "TA cells",
    Classification == "I1" ~ "Goblet",
    Classification == "J1" ~ "Colonocytes",
    Classification == "K1" ~ "Blood",
    Classification == "L1" ~ "Endocrine",
    Classification == "M1" ~ "Blood",
    Classification == "N1" ~ "Stem",
    Classification == "O1" ~ "TA cells",
    Classification == "P1" ~ "Goblet"
  )) %>%
  ggplot() +
  geom_tile(aes(plate, Classification, fill = percent)) +
  viridis::scale_fill_viridis() +
  facet_wrap(~ supervisedClass, ncol = 1, scales = "free") +
  labs(
    x = "Plate", 
    caption = "'Percent' indicates the percentage of cells in a class from the specified plate."
  ) +
  ggthemes::theme_few() +
  theme(plot.caption = element_text(hjust = 0)) +
  guides(fill = guide_colorbar(title = "Percent"))
```

## Small Intestine
```{r, fig.align="center", fig.width=10, fig.height=8}
plotUnsupervisedClass(uObjSi, cObjSngSi)

plotUnsupervisedMarkers(
  uObjSi, cObjSngSi, 
  c("Lgr5", "Muc2", "Ptprc", "Chga", "Alpi", "Lyz1", "Dclk1"), 
  pal = RColorBrewer::brewer.pal(7, "Set2")
)

plotUnsupervisedMarkers(uObjSi, cObjSngSi, c("Mki67"))
```


```{r, fig.align="center", fig.width=12, fig.height=10, eval = FALSE, echo = FALSE}
plotUnsupervisedClass(uObjSi, cObjSngSi) %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(plate = if_else(str_detect(Sample, "SRR"), "Regev", plate)) %>%
  count(plate, Classification) %>%
  spread(plate, n, fill = 0) %>%
  gather(plate, n, -Classification) %>%
  group_by(plate) %>%
  mutate(percent = 100 * (n / sum(n))) %>%
  mutate(supervisedClass = case_when(
    Classification == "A1" ~ "Blood",
    Classification == "B1" ~ "TA cells",
    Classification == "C1" ~ "Goblet",
    Classification == "D1" ~ "Enterocytes",
    Classification == "E1" ~ "Stem",
    Classification == "F1" ~ "TA cells",
    Classification == "G1" ~ "TA cells",
    Classification == "H1" ~ "Enterocytes",
    Classification == "I1" ~ "Endocrine",
    Classification == "J1" ~ "Tufft",
    Classification == "K1" ~ "Stem",
    Classification == "L1" ~ "Stem",
    Classification == "M1" ~ "Stem",
    Classification == "N1" ~ "Blood",
    Classification == "O1" ~ "TA cells",
    Classification == "P1" ~ "Stem",
    Classification == "Q1" ~ "Paneth",
    TRUE ~ "error"
    )) %>%
  ggplot() +
  geom_tile(aes(plate, Classification, fill = percent)) +
  facet_wrap(~ supervisedClass, ncol = 1, scales = "free") +
  viridis::scale_fill_viridis() +
  labs(
    x = "Plate", 
    caption = "'Percent' indicates the percentage of cells in a class from the specified plate."
  ) +
  ggthemes::theme_few() +
  theme(plot.caption = element_text(hjust = 0)) +
  guides(fill = guide_colorbar(title = "Percent"))
```

## All
```{r, fig.align="center", fig.width=10, fig.height=8}
plotUnsupervisedClass(uObj, cObjSng)
plotUnsupervisedMarkers(
  uObj, cObjSng,
  c("Lgr5", "Muc2", "Ptprc", "Chga", "Alpi", "Lyz1", "Dclk1", "Slc40a1"), 
  pal = RColorBrewer::brewer.pal(8, "Set1")
)

plotUnsupervisedClass(uObj, cObjSng) %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(tissue = if_else(str_detect(Sample, "SRR"), "SI", tissue)) %>%
  ggplot() +
  geom_point(aes(`t-SNE dim 1`, `t-SNE dim 2`, colour = tissue)) +
  ggthemes::theme_few()

plotUnsupervisedClass(uObj, cObjSng) %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(tissue = if_else(str_detect(Sample, "SRR"), "SI", tissue)) %>%
  mutate(plate = if_else(is.na(plate), "Regev", plate)) %>%
  ggplot() +
  geom_point(aes(`t-SNE dim 1`, `t-SNE dim 2`, colour = plate), alpha = 0.75) +
  ggthemes::theme_few() +
  scale_colour_manual(values = col40())

plotUnsupervisedClass(uObj, cObjSng) %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(total.counts = map_dbl(Sample, function(s) {
    sum(getData(cObjSng, "counts")[, s])
  })) %>%
  mutate(total.counts.bin = ntile(total.counts, 10)) %>%
  group_by(total.counts.bin) %>%
  mutate(total.counts.mean = mean(total.counts)) %>%
  ggplot() +
  geom_point(aes(`t-SNE dim 1`, `t-SNE dim 2`, colour = total.counts.mean)) +
  ggthemes::theme_few() +
  viridis::scale_colour_viridis(option = "E") +
  guides(colour = guide_colorbar(title = "Binned total counts")) +
  labs(caption = paste0(
    "Total counts were calculated for each sample. The total counts were then ",
    "evenly divided into 10 bins for the whole dataset and the mean\n ",
    "total counts calculated for each bin. This mean was then portrayed as the ",
    "point colour in the figure."
  )) +
  theme(
    plot.caption = element_text(hjust = 0)
  )

plotUnsupervisedClass(uObj, cObjSng) %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(total.counts = map_dbl(Sample, function(s) {
    sum(getData(cObjSng, "counts")[, s])
  })) %>%
  mutate(total.counts.bin = ntile(total.counts, 10)) %>%
  group_by(total.counts.bin) %>%
  mutate(total.counts.mean = mean(total.counts)) %>%
  mutate(Regev = if_else(str_detect(Sample, "SRR"), TRUE, FALSE)) %>%
  ggplot() + 
  geom_boxplot(aes(Regev, total.counts)) +
  theme_bw()
```

### Paneth

```{r, fig.align="center", fig.width=10, fig.height=8}
plotUnsupervisedMarkers(uObj, cObjSng, "Lyz1") %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(regev = if_else(str_detect(Sample, "SRR"), TRUE, FALSE)) %>%
  filter(Classification == "S1") %>%
  ggplot() +
  geom_point(
    aes(`t-SNE dim 1`, `t-SNE dim 2`, shape = regev, colour = Lyz1), 
    size = 3
  ) +
  viridis::scale_colour_viridis(option = "E") + 
  theme_few()

plotUnsupervisedMarkers(uObj, cObjSng, "Defa24") %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(regev = if_else(str_detect(Sample, "SRR"), TRUE, FALSE)) %>%
  filter(Classification == "S1") %>%
  ggplot() +
  geom_point(
    aes(`t-SNE dim 1`, `t-SNE dim 2`, shape = regev, colour = Defa24), 
    size = 3
  ) +
  viridis::scale_colour_viridis(option = "E") + 
  theme_few()

plotUnsupervisedMarkers(uObj, cObjSng, "Defa17") %>%
  plotData() %>%
  full_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  filter(!is.na(`t-SNE dim 1`)) %>%
  mutate(regev = if_else(str_detect(Sample, "SRR"), TRUE, FALSE)) %>%
  filter(Classification == "S1") %>%
  ggplot() +
  geom_point(
    aes(`t-SNE dim 1`, `t-SNE dim 2`, shape = regev, colour = Defa17), 
    size = 3
  ) +
  viridis::scale_colour_viridis(option = "E") + 
  theme_few()

d <- plotUnsupervisedClass(uObj, cObjSng) %>%
  plotData() %>%
  inner_join(countsMgfpMeta, by = c("Sample" = "sample")) %>%
  select(Sample, Classification, plate:column, mouseID) %>%
  filter(Classification == "S1") %>%
  mutate(total.counts = map_dbl(Sample, function(s) {
    sum(getData(cObjSng, "counts")[, s])
  })) %>%
  mutate(Lyz1.cpm = map_dbl(Sample, function(s) {
    getData(cObjSng, "counts")["Lyz1", s]
  })) %>%
  mutate(Defa24.cpm = map_dbl(Sample, function(s) {
    getData(cObjSng, "counts")["Defa24", s]
  })) %>%
  mutate(Defa17.cpm = map_dbl(Sample, function(s) {
    getData(cObjSng, "counts")["Defa17", s]
  }))

as.data.frame(d)
```


