---
title: "Mouse analysis enge"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
packages <- c("CIMseq", "CIMseq.data", "tidyverse", "ggthemes")
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

##DATA
load('../data/CIMseqData.rda')
load('../data/sObj.rda')
```

```{r, eval = TRUE, echo = FALSE}
#rename classes
renameClasses <- function(class) {
  case_when(
    class == "0" ~ "C.Colonocytes",
    class == "1" ~ "SI.Lgr5+",
    class == "2" ~ "C.Distal.Lgr5+",
    class == "3" ~ "C.Lgr5+.Ki67",
    class == "4" ~ "C.Distal.TA",
    class == "5" ~ "C.Proximal.Lgr5+.1",
    class == "6" ~ "SI.Lgr5+.Mki67h",
    class == "7" ~ "C.Proximal.TA",
    class == "8" ~ "C.Distal.Goblet.marker",
    class == "9" ~ "C.Proximal.Goblet",
    class == "10" ~ "C.Distal.Goblet.Fos",
    class == "11" ~ "SI.Goblet",
    class == "12" ~ "C.Distal.Goblet.Plet1",
    class == "13" ~ "SI.TA.1",
    class == "14" ~ "SI.Lgr5+.Mki67l",
    class == "15" ~ "C.Proximal.Lgr5+.2",
    class == "16" ~ "Enteroendocrine",
    class == "17" ~ "Tufft",
    class == "18" ~ "SI.Enterocytes",
    class == "19" ~ "SI.TA.2",
    class == "20" ~ "SI.Paneth",
    class == "21" ~ "C.Distal.Goblet.Mki67",
    class == "22" ~ "Blood",
    TRUE ~ "error"
  )
}

cOrder <- c(
  "SI.Goblet", "SI.Paneth", "SI.Lgr5+", "SI.Lgr5+.Mki67l", "SI.Lgr5+.Mki67h", "SI.TA.1", "SI.TA.2", "SI.Enterocytes",
  "C.Proximal.Goblet", "C.Proximal.Lgr5+.1", "C.Proximal.Lgr5+.2", "C.Proximal.TA", "C.Colonocytes", "C.Lgr5+.Ki67",
  "C.Distal.Goblet.Mki67", "C.Distal.Goblet.Plet1", "C.Distal.Goblet.Fos", "C.Distal.Goblet.marker", "C.Distal.Lgr5+", "C.Distal.TA",
  "Enteroendocrine", "Tufft", "Blood"
)

getData(cObjSng, "classification") <- renameClasses(getData(cObjSng, "classification"))
fractions <- getData(sObj, "fractions")
colnames(fractions) <- renameClasses(colnames(fractions))
sObj@fractions <- fractions
```

```{r, fig.align="center", fig.width=10, fig.height=8}
p <- plotUnsupervisedClass(cObjSng, cObjMul)
p
ggsave(
  plot = p,
  filename = '../figures/MGA.enge.classes.pdf',
  device = cairo_pdf,
  height = 180,
  width = 180,
  units = "mm"
)
p <- plotUnsupervisedMarkers(
  cObjSng, cObjMul,
  c("Lgr5", "Ptprc", "Chga", "Dclk1", "Alpi", "Slc26a3", "Atoh1", "Lyz1"),
  pal = RColorBrewer::brewer.pal(8, "Set1")
)
ggsave(
  plot = p,
  filename = '../figures/MGA.enge.markers.pdf',
  device = cairo_pdf,
  height = 180,
  width = 180,
  units = "mm"
)

p <- plotUnsupervisedMarkers(cObjSng, cObjMul, "Mki67")
ggsave(
  plot = p,
  filename = '../figures/MGA.enge.Mki67.pdf',
  device = cairo_pdf,
  height = 180,
  width = 180,
  units = "mm"
)

p <- plotUnsupervisedMarkers(cObjSng, cObjMul, "Hoxb13")
ggsave(
  plot = p,
  filename = '../figures/MGA.enge.Hoxb13.pdf',
  device = cairo_pdf,
  height = 180,
  width = 180,
  units = "mm"
)
```

```{r, eval = FALSE}
classHeatmap(
  data = data.frame(
    gene = markers$gene,
    class = markers$cluster
  ),
  counts.log = getData(cObjSng, "counts.log"),
  classes = tibble(
    sample = colnames(getData(cObjSng, "counts")), 
    class = getData(cObjSng, "classification")
  )
)
```

Markers barplot
```{r, fig.align="center", fig.width=12, fig.height=10}
markers <- c(
  "Lgr5", "Ptprc", "Chga", "Dclk1", "Alpi", "Slc26a3", "Atoh1", "Lyz1", "Mki67",
  "Hoxb13", "Plet1", "Osr2", "Reg4", "Sval1"
)

gene.order <- c(
  "Hoxb13", "Osr2", "Atoh1", "Reg4", "Sval1", "Plet1", "Mki67", "Lgr5", "Alpi", 
  "Slc26a3", "Lyz1", "Dclk1", "Chga", "Ptprc"
)

d <- getData(cObjSng, "counts.cpm")[markers, ] %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Sample") %>%
  as_tibble() %>% 
  gather(gene, cpm, -Sample) %>%
  inner_join(tibble(
    Sample = colnames(getData(cObjSng, "counts")), 
    Classification = getData(cObjSng, "classification")
  )) %>%
  mutate(Classification = parse_factor(Classification, levels = cOrder)) %>%
  mutate(gene = parse_factor(gene, levels = gene.order)) %>%
  arrange(Classification, gene) %>%
  mutate(Sample = parse_factor(Sample, levels = unique(Sample))) %>% 
  mutate(type = case_when(
    str_detect(Classification, "^S") ~ "Small intestine",
    str_detect(Classification, "^C") ~ "Colon",
    TRUE ~ "Other"
  )) %>%
  mutate(type = parse_factor(
    type,
    levels = c("Small intestine", "Colon", "Other")
  ))

under <- d %>%
  mutate(idx = 1:nrow(.)) %>% 
  group_by(Classification) %>% 
  summarize(
    min = (min(idx)), max = (max(idx) - 1), median = median(idx)
  ) %>%
  ggplot() +
  geom_segment(
    aes(x = min, xend = max, y = 0, yend = 0, colour = Classification)
  ) +
  geom_text(
    aes(median, y = 0, label = Classification),
    angle = 90, nudge_y = -0.01, hjust = 1, colour = "grey10"
  ) +
  scale_colour_manual(values = col40()) +
  ylim(c(-1, 0)) +
  theme_few() +
  scale_x_continuous(expand = c(0, 0)) +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = FALSE)

over <- d %>% 
  ggplot() + 
  geom_bar(aes(Sample, cpm, fill = Classification), stat = "identity") + 
  facet_grid(gene ~ type, scales = "free", space = "free_x") +
  scale_fill_manual(values = col40()) +
  theme_few() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    strip.background.x = element_rect(fill = "white")
  ) +
  labs(y = "CPM") +
  guides(fill = FALSE)

library(patchwork)

p <- over + under + plot_layout(ncol = 1, heights = c(2, 1))
p
ggsave(
  plot = p,
  filename = '../figures/MGA.enge.geneBar.pdf',
  device = cairo_pdf,
  height = 300,
  width = 300,
  units = "mm"
)
```

Markers dotplot
```{r, fig.align="center", fig.width=10, fig.height=8}
scale.func <- scale_radius
scale.min <- NA
scale.max <- NA

p <- d %>%
  mutate(gene = forcats::fct_rev(factor(gene))) %>%
  group_by(gene, Classification) %>%
  summarize(mean = mean(cpm), pct = 100 * (length(which(cpm != 0)) / n())) %>%
  mutate(scaled.mean.exp = scale(mean)) %>%
  ggplot() +
  geom_point(
    aes(Classification, gene, size = pct, colour = scaled.mean.exp)
  ) +
  scale_color_gradient(low = "white", high = "darkred") +
  scale.func(range = c(0, 12), limits = c(scale.min, scale.max)) +
  guides(
    size = guide_legend(
      title = "% expressed", title.position = "top", title.hjust = 0.5
    ),
    colour = guide_colorbar(
      title = "Scaled mean expression", title.position = "top", 
      title.hjust = 0.5, barwidth = 10
    )
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1), 
    axis.title = element_blank(), 
    legend.position = "top",
    legend.justification = "center"
  )
p
ggsave(
  plot = p,
  filename = '../figures/MGA.enge.geneDot.pdf',
  device = cairo_pdf,
  height = 300,
  width = 300,
  units = "mm"
)
```

Stemness dotplot
```{r, fig.align="center", fig.width=10, fig.height=8}
load('../data/seurat.rda')
markers <- c("Wnt3", "Wnt2b", "Wnt4", "Wnt5a", "Lgr5", "Axin2", "Ascl2")
gene.order <- markers

d <- getData(cObjSng, "counts.cpm")[markers, ] %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Sample") %>%
  as_tibble() %>% 
  gather(gene, cpm, -Sample) %>%
  inner_join(tibble(
    Sample = colnames(getData(cObjSng, "counts")), 
    Classification = getData(cObjSng, "classification")
  ), by = "Sample") %>%
  mutate(Classification = parse_factor(Classification, levels = cOrder)) %>%
  mutate(gene = parse_factor(gene, levels = gene.order)) %>%
  arrange(Classification, gene) %>%
  mutate(Sample = parse_factor(Sample, levels = unique(Sample)))


#scale.func <- scale_size
scale.func <- scale_radius
scale.min <- NA
scale.max <- NA

p <- d %>%
  mutate(gene = forcats::fct_rev(factor(gene))) %>%
  group_by(gene, Classification) %>%
  summarize(mean = mean(cpm), pct = 100 * (length(which(cpm != 0)) / n())) %>%
  mutate(scaled.mean.exp = scale(mean)) %>%
  mutate(type = case_when(
    str_detect(gene, "^Wnt") ~ "Wnt ligand",
    gene == "Fzd9" ~ "Receptor",
    TRUE ~ "Wnt target"
  )) %>%
  mutate(type = parse_factor(type, levels = c("Wnt ligand", "Receptor", "Wnt target"))) %>%
  ggplot() +
  geom_point(
    aes(Classification, gene, size = pct, colour = scaled.mean.exp)
  ) +
  facet_grid(type ~ ., space = "free", scales = "free") +
  scale_color_gradient(low = "white", high = "darkred") +
  scale.func(range = c(0, 16), limits = c(scale.min, scale.max)) +
  guides(
    size = guide_legend(
      title = "% expressed", title.position = "top", title.hjust = 0.5
    ),
    colour = guide_colorbar(
      title = "Scaled mean expression", title.position = "top", 
      title.hjust = 0.5, barwidth = 10
    )
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1), 
    axis.title = element_blank(), 
    legend.position = "top",
    legend.justification = "center"
  )
p
ggsave(
  plot = p,
  filename = '../figures/MGA.enge.stemness.dotplot.pdf',
  device = cairo_pdf,
  height = 300,
  width = 300,
  units = "mm"
)
```

```{r, fig.align="center", fig.width=14, fig.height=12, eval = TRUE}
plotSwarmCircos(sObj, cObjSng, cObjMul, weightCut = 0, classOrder = cOrder)
```

Detected duplicates - quadruplicates.  
Only ERCC estimated cell number max 4.  
Weight cutoff = 10.

```{r, fig.align="center", fig.width=14, fig.height=12, eval = TRUE}
adj <- adjustFractions(cObjSng, cObjMul, sObj, binary = TRUE)
samples <- rownames(adj)
rs <- rowSums(adj)
keep <- rs == 2 | rs == 3 | rs == 4

plotSwarmCircos(
  filterSwarm(sObj, keep), cObjSng, cObjMul, weightCut = 10, 
  classOrder = cOrder, alpha = 0.01
)

pdf('../figures/MGA.enge.circos.pdf', width = 12, height = 10)
plotSwarmCircos(
  filterSwarm(sObj, keep), cObjSng, cObjMul, weightCut = 10, 
  classOrder = cOrder, alpha = 0.01
)
invisible(dev.off())


```



