---
title: "Testing Poisson Swarm Algorithm with Sorted Multiplets Dataset"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
#PACKAGES
packages <- c(
  "sp.scRNAseq", "sp.scRNAseqData", "sp.scRNAseqTesting",
  "printr", "ggthemes", "tidyverse"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

##DATA
load("~/Github/sp.scRNAseqTesting/inst/testingPoissonSorted/data/sObj.rda")
```

### Show average stats for multiplets dependant on the number of cell in the multiplet.
```{r, fig.align="center", fig.width=10, fig.height=8}
known <- setupPlate(countsSortedMeta2)
res <- checkResults(sObj, known, 0)

res %>%
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  mutate(cellsInMultiplet = str_count(cellTypes, "-") + 1) %>%
  group_by(cellsInMultiplet) %>%
  summarize(
    meanTPR = mean(TPR, na.rm = TRUE),
    meanTNR = mean(TNR, na.rm = TRUE),
    meanACC = mean(ACC, na.rm = TRUE)
  )

res %>% 
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  mutate(cellsInMultiplet = str_count(cellTypes, "-") + 1) %>%
  ggplot() +
  geom_dotplot(
    aes(cellsInMultiplet, ACC, group = cellsInMultiplet), 
    binaxis = "y", binwidth = 0.01, dotsize = 0.75, stackdir = "center"
  ) + 
  theme_bw() +
  scale_y_continuous(breaks = seq(0, 1, 0.2), limits = c(0, 1)) +
  labs(x = "Cell types", y = "Accuracy")
```

### Show average stats for multiplets dependant on the combination of cells in the multiplet.
```{r, fig.align="center", fig.width=10, fig.height=8}
res %>%
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  mutate(cellsInMultiplet = str_count(cellTypes, "-") + 1) %>%
  group_by(cellTypes) %>%
  summarize(
    meanTPR = mean(TPR, na.rm = TRUE),
    meanTNR = mean(TNR, na.rm = TRUE),
    meanACC = mean(ACC, na.rm = TRUE)
  )

res %>% 
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  mutate(cellsInMultiplet = str_count(cellTypes, "-") + 1) %>%
  arrange(cellsInMultiplet) %>%
  mutate(cellTypes = parse_factor(cellTypes, levels = unique(cellTypes))) %>%
  ggplot() +
  geom_dotplot(
    aes(
      cellTypes, ACC, group = cellTypes, fill = factor(cellsInMultiplet), 
      colour = factor(cellsInMultiplet)
    ),
    binaxis = "y", binwidth = 0.01, dotsize = 0.75, stackdir = "center"
  ) +
  theme_bw() +
  scale_fill_ptol() +
  scale_colour_ptol() +
  scale_y_continuous(breaks = seq(0, 1, 0.2), limits = c(0, 1)) +
  labs(x = "Cell types", y = "Accuracy") +
  theme(axis.text.x = element_text(angle = 90)) +
  guides(
    fill = guide_legend(title = "# of cells in multiplet"), 
    colour = guide_legend(title = "# of cells in multiplet")
  )
```

### Print all stats.
```{r}
print <- res %>% 
  mutate(connections.detected = map_chr(data.detected, function(x) paste(unlist(x), collapse = ", "))) %>%
  mutate(connections.expected = map_chr(data.expected, function(x) paste(unlist(x), collapse = ", "))) %>%
  select(-(data.detected:data.expected)) %>%
  inner_join(countsSortedMeta2, by = c("multiplet" = "sample")) %>%
  select(-(plate:cellNumber)) %>%
  rename(cellsSorted = cellTypes) %>%
  inner_join(matrix_to_tibble(getData(sObj, "spSwarm"), "multiplet"), by = "multiplet") %>%
  mutate(HOS = round(HOS, digits = 5), HCT116 = round(HCT116, digits = 5), A375 = round(A375, digits = 5)) %>%
  unite(fractions, HOS, HCT116, A375, sep = ", ") %>%
  rename("fractions (HOS, HCT116, A375)" = fractions) %>%
  select(multiplet, cellsSorted, connections.expected, connections.detected, `fractions (HOS, HCT116, A375)`, tp:ACC)

as.data.frame(print)
```


