---
title: "Mouse analysis"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
packages <- c("sp.scRNAseq", "sp.scRNAseqData", "tidyverse")
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

##DATA
load('../data/uObj.rda')
load('../data/sObj.rda')
```

```{r, warning=FALSE}
#setup spCounts
keep.plates.SI <- c("NJA01202", "NJA01301", "NJA01302")
keep.plates.colon <- c("NJA01303", "NJA01401", "NJA01205", "NJA00609")

s <- str_detect(colnames(countsMgfp), "^s")
e <- colnames(countsMgfp) %in% filter(countsMgfpMeta, is.na(GFP) & !filtered & plate %in% c(keep.plates.SI, keep.plates.colon))$sample
boolSng <- s & e
boolMul <- !s & e

cObjSng <- spCounts(countsMgfp[, boolSng], countsMgfpERCC[, boolSng])
cObjMul <- spCounts(countsMgfp[, boolMul], countsMgfpERCC[, boolMul])
```

```{r, fig.align="center", fig.width=10, fig.height=8}
renameClasses <- function(class) {
  case_when(
    class == "1" ~ "C.Stem",
    class == "2" ~ "SI.Stem.1",
    class == "3" ~ "SI.TA.early",
    class == "4" ~ "C.Goblet.1",
    class == "5" ~ "C.Colonocyte",
    class == "6" ~ "C.Goblet.2",
    class == "7" ~ "SI.Stem.2",
    class == "8" ~ "SI.Goblet",
    class == "9" ~ "SI.TA.intermediate",
    class == "10" ~ "SI.TA.late",
    class == "11" ~ "Tufft",
    class == "12" ~ "Endocrine",
    class == "13" ~ "Paneth",
    class == "14" ~ "SI.Enterocyte",
    class == "15" ~ "C.TA",
    class == "undefined" ~ "undefined", 
    TRUE ~ "error"
  )
}
classification(uObj) <- renameClasses(getData(uObj, "classification"))
plotUnsupervisedClass(uObj, cObjSng)
plotUnsupervisedMarkers(
  uObj, cObjSng,
  c("Lgr5", "Muc2", "Ptprc", "Chga", "Alpi", "Lyz1", "Dclk1", "Slc40a1"), 
  pal = RColorBrewer::brewer.pal(8, "Set1")
)
```

```{r, fig.align="center", fig.width=12, fig.height=10}
swarm <- getData(sObj, "spSwarm")
swarm <- swarm[, colnames(swarm) != "undefined"]

edgeDat <- getEdgesForMultiplet(sObj, 0.001, rownames(swarm)) %>%
  filter(from != "undefined" & to != "undefined") %>%
  group_by(multiplet) %>%
  summarize(edges = paste(paste(from, to, sep = "-"), collapse = ", "))

p <- swarm %>%
  add_column(cd = apply(., 1, function(f) length(which(f != 0)))) %>%
  rownames_to_column("sample") %>%
  as_tibble() %>%
  gather(class, fraction, -sample, -cd) %>%
  mutate(classTissue = case_when(
    class %in% c("5", "1", "15", "6", "4") ~ "colon", 
    class %in% c("10", "13", "14", "2", "3", "7", "8", "9") ~ "SI",
    class %in% c("12", "11") ~ "miscellaneous", 
    TRUE ~ "error"
  )) %>%
  inner_join(countsMgfpMeta, by = "sample") %>%
  mutate(class = renameClasses(class)) %>%
  inner_join(edgeDat, by = c("sample" = "multiplet")) %>%
  arrange(edges) %>%
  mutate(sample = parse_factor(sample, levels = unique(sample))) %>%
  ggplot() +
  geom_tile(aes(class, sample, fill = log2(fraction + 1))) +
  facet_grid(. ~ classTissue, scales = "free") +
  scale_fill_viridis_c() +
  theme_bw() +
  labs(x = "Samples", caption = "edge cutoff = 0") +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 90),
    legend.position = "top",
    plot.caption = element_text(hjust = 0)
  ) +
  guides(fill = guide_colourbar(title = "Fraction", title.position = "top", title.hjust = 0.5))

p
```

```{r, fig.align="center", fig.width=12, fig.height=10}
p <- round(swarm, digits = 2) %>%
  add_column(cd = apply(., 1, function(f) length(which(f != 0)))) %>%
  rownames_to_column("sample") %>%
  as_tibble() %>%
  gather(class, fraction, -sample, -cd) %>%
  mutate(classTissue = case_when(
    class %in% c("5", "1", "15", "6", "4") ~ "colon", 
    class %in% c("10", "13", "14", "2", "3", "7", "8", "9") ~ "SI",
    class %in% c("12", "11") ~ "miscellaneous", 
    TRUE ~ "error"
  )) %>%
  inner_join(countsMgfpMeta, by = "sample") %>%
  mutate(class = renameClasses(class)) %>%
  inner_join(edgeDat, by = c("sample" = "multiplet")) %>%
  arrange(edges) %>%
  mutate(sample = parse_factor(sample, levels = unique(sample))) %>%
  ggplot() +
  geom_tile(aes(class, sample, fill = log2(fraction + 1))) +
  facet_grid(cd ~ classTissue, scales = "free") +
  scale_fill_viridis_c() +
  theme_bw() +
  labs(x = "Samples", caption = "edge cutoff = 0.01") +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 90),
    legend.position = "top",
    plot.caption = element_text(hjust = 0)
  ) +
  guides(fill = guide_colourbar(title = "Fraction", title.position = "top", title.hjust = 0.5))

p
```

```{r, fig.align="center", fig.width=12, fig.height=10}
spSwarmPoisson(sObj, 0.001) %>%
  filter(from != "undefined" & to != "undefined") %>%
  arrange(from, to) %>%
  mutate(
    from.name = renameClasses(from),
    to.name = renameClasses(to)
  ) %>%
  mutate(
    from.name = parse_factor(from.name, levels = unique(from.name)),
    to.name = parse_factor(to.name, levels = unique(to.name))
  ) %>%
  ggplot() +
  geom_tile(aes(from.name, to.name, fill = weight)) +
  scale_fill_viridis_c() +
  labs(x = "from", y = "to", caption = "edge.cutoff = 0.01") +
  theme(
    plot.caption = element_text(hjust = 0),
    axis.text.x = element_text(angle = 90),
    legend.position = "top"
  ) +
  guides(fill = guide_colourbar(title = "Weight", title.position = "top", title.hjust = 0.5))
```

```{r, fig.align="center", fig.width=12, fig.height=10}
weights <- spSwarmPoisson(sObj, 0.1)

freq <- expand.grid(colnames(swarm), colnames(swarm), stringsAsFactors = FALSE) %>%
  as_tibble() %>%
  mutate(weight = map2_int(Var1, Var2, function(f, t) {
    filter(weights, (from == f & to == t) | (from == t & to == f))$weight
  })) %>%
  group_by(Var1) %>%
  mutate(totalWeights = sum(weight)) %>%
  ungroup() %>%
  mutate(Frequency = weight / totalWeights)

data <- spSwarmPoisson(sObj, 0.1) %>%
  filter(from != "undefined" & to != "undefined") %>%
  arrange(from, to) %>%
  mutate(
    from.name = renameClasses(from),
    to.name = renameClasses(to)
  ) %>%
  mutate(
    from.name = parse_factor(from.name, levels = unique(from.name)),
    to.name = parse_factor(to.name, levels = unique(to.name))
  ) %>%
  inner_join(freq, by = c("from" = "Var1", "to" = "Var2"))


data %>%
  ggplot() +
  geom_tile(aes(from.name, to.name, fill = Frequency)) +
  scale_fill_viridis_c() +
  labs(x = "from", y = "to", caption = "edge.cutoff = 0.01; 'Frequency' is the frequency of 'from' interaction with 'to'.") +
  theme(
    plot.caption = element_text(hjust = 0),
    axis.text.x = element_text(angle = 90),
    legend.position = "top"
  ) +
  guides(fill = guide_colourbar(title = "Frequency", title.position = "top", title.hjust = 0.5))
```

