---
title: "Determine edge cutoff for sorted multiplet dataset"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
#PACKAGES
packages <- c(
  "sp.scRNAseq", "sp.scRNAseqData", "sp.scRNAseqTesting", "printr",
  "ggthemes", "tidyverse", "viridis"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

#DATA
load('../data/determineEdgeCutoff.rda')
load('../../testingPoissonSorted/data/uObj.rda')
```


```{r, fig.align="center", fig.height=10, fig.width=12}
edgeData %>% 
  mutate(interval = parse_factor(interval, levels = sort(as.numeric(interval)))) %>% 
  ggplot() + 
  geom_jitter(aes(edges, interval), width = 0.1, height = 0.1) + 
  facet_grid(combo ~ celltype_reduced) + 
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Detected edges", y = "Contribution", caption = "Reduced contribution cell type on x-axis panels. Other cell type in duplicate shown on y-axis panels.") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90), plot.caption = element_text(hjust = 0))
```

```{r, fig.align="center", fig.height=10, fig.width=12}
uClass <- sort(unique(getData(uObj, "classification")))
d <- getData(swarm, "spSwarm") %>%
  rownames_to_column("info") %>%
  as_tibble() %>%
  separate(info, into = c("celltype_reduced", "interval", "repetition", "combo"), sep = "_") %>%
  nest(-(celltype_reduced:combo)) %>%
  mutate(expected = paste0(celltype_reduced, "-", combo)) %>%
  mutate(edges = pmap(list(data, expected, celltype_reduced, combo), function(d, e, ct1, ct2) {
    mat <- matrix(as.numeric(as.data.frame(d)[1, ]), nrow = 1, dimnames = list(NULL, uClass))
    logic <- sp.scRNAseq:::.fractionCutoff(mat, cutoff = 0)
    sp.scRNAseq:::.calculateWeight(mat, logic) %>%
      filter(weight > 0) %>% 
      mutate(correct = if_else(paste0(from, "-", to) == e | paste0(to, "-", from) == e, TRUE, FALSE)) %>%
      mutate(
        from_frac = pmap(list(from, correct, ct1, ct2), function(f, c, c1, c2) {
          if_else(!c & f %in% c(c1, c2), NaN, mat[, colnames(mat) == f])
        }),
        to_frac = pmap(list(to, correct, ct1, ct2), function(t, c, c1, c2) {
          if_else(!c & t %in% c(c1, c2), NaN, mat[, colnames(mat) == t])
        })
      )
  })) %>%
  select(-data) %>%
  unnest() %>%
  unnest() %>%
  gather(direction, frac, -(celltype_reduced:correct)) %>%
  mutate(interval = parse_factor(interval, levels = rev(sort(as.numeric(interval))))) %>%
  filter(!is.nan(frac))

#d %>% 
#  ggplot() +
#  geom_histogram(aes(frac, fill = correct), position = position_dodge(), binwidth = 0.01) +
#  facet_wrap(~interval) +
#  labs(x = "Fractions") +
#  theme_bw()

d %>%
  filter(frac != 0) %>%
  ggplot() +
  geom_histogram(aes(-log10(frac), fill = correct), position = position_dodge(), binwidth = 0.1) +
  facet_wrap(~interval) +
  theme_bw() +
  theme(legend.position = "top") +
  labs(x = "-log10(Detected fraction)", y = "Count") +
  guides(fill = guide_legend(title = "Correct edge"))
```


```{r, fig.align="center", fig.height=10, fig.width=12}
edgeData %>%
  mutate(interval = as.numeric(interval)) %>% 
  select(-data) %>%
  mutate(mat = map(mat, ~matrix_to_tibble(.x))) %>%
  unnest() %>%
  select(-rowname) %>%
  gather(celltype_frac, frac, -(celltype_reduced:edges)) %>%
  filter(celltype_reduced == celltype_frac) %>%
  filter(frac != 0) %>%
  ggplot() + 
  geom_point(aes(interval, frac)) +
  scale_x_log10(breaks = c(1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.5)) +
  scale_y_log10() +
  theme_bw() +
  labs(x = "Expected fraction", y = "Observed fraction")
```

