---
title: "Testing new swarm algo"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
#PACKAGES
packages <- c(
  "CIMseq","CIMseq.data", "CIMseq.testing", "printr", "ggplot2",
  "ggthemes", "tidyr", "future", "patchwork", "dplyr", "purrr"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

##DATA
load('../../SCM.analysis/data/CIMseqData.rda')
load('../../SCM.analysis/data/sObj.rda')
load('../data/syntheticMultiplets.rda')

renameClasses <- function(class) {
  case_when(
    class == "0" ~ "A375",
    class == "1" ~ "HCT116",
    class == "2" ~ "HOS",
    TRUE ~ "error"
  )
}

getData(cObjSng, "classification") <- renameClasses(getData(cObjSng, "classification"))
fractions <- getData(sObj, "fractions")
colnames(fractions) <- renameClasses(colnames(fractions))
sObj@fractions <- fractions
```

Show marker gene expression

```{r, fig.align="center", fig.height=8, fig.width=10}
#ANXA3 = HCT116 marker
#CD74 = A375 marker
#ACTG2 = HOS marker
g <- c("ANXA3", "CD74", "ACTG2")

#plot genes in singlets
p1 <- getData(cObjSng, "counts.cpm")[g, ] %>% 
  matrix_to_tibble("gene") %>%
  gather(sample, value, -gene) %>%
  inner_join(SCM.Meta, by = "sample") %>%
  mutate(gene = case_when(
    gene == "ANXA3" ~ "HCT116: ANXA3",
    gene == "CD74" ~ "A375: CD74",
    gene == "ACTG2" ~ "HOS: ACTG2",
    TRUE ~ "error"
  )) %>%
  ggplot() +
  geom_boxplot(
    aes(cellTypes, value, colour = gene),
    notch = TRUE, lwd = 0.5, outlier.size = 0.4
  ) +
  coord_flip() +
  scale_colour_ptol() +
  theme_few() +
  labs(y = "CPM") +
  guides(colour = guide_legend(title = "Gene")) + 
  theme(axis.title.y = element_blank())

p1 
```

```{r, fig.align="center", fig.height=8, fig.width=10}
#poisson distribution of each synthetic multiplet value
poissonDistSM <- synthetic.mul %>%
  mutate(pos = list(seq(0, max(value) + 200, 10))) %>%
  mutate(ind.dpois = map2(value, pos, ~dpois(.y, .x))) %>%
  unnest() %>%
  group_by(gene, type) %>%
  mutate(
    ind.dpois.norm = (ind.dpois - min(ind.dpois)) / (max(ind.dpois) - min(ind.dpois))
  )

#calculate dpois only for the real synthetic multiplet values to be able to 
#show the real mean cost per gene
realCost <- synthetic.mul %>%
  mutate(dpois.real = map2_dbl(real.multiplet, value, ~dpois(.x, .y, FALSE))) %>%
  group_by(gene, type) %>%
  summarize(mean.dpois = mean(dpois.real)) %>%
  ungroup() %>%
  mutate(mean.log = log10(mean.dpois)) %>%
  mutate(cost.real = if_else(is.infinite(mean.log), 323.0052, mean.log * - 1))

#calculate the entire cost space (blue line)
entireCost <- synthetic.mul %>%
  mutate(dpois.x = list(round(seq(0, max(value), 1)))) %>%
  unnest() %>%
  mutate(dpois = dpois(dpois.x, value)) %>%
  group_by(gene, type, dpois.x) %>%
  summarize(mean = mean(dpois)) %>%
  mutate(mean.log = log10(mean)) %>%
  mutate(cost = if_else(is.infinite(mean.log), 323.005, mean.log * - 1)) %>%
  ungroup() %>%
  mutate(cost.norm = (cost - min(cost)) / (max(cost) - min(cost)))

max.cost <- max(entireCost$cost)

#isolate the real multiplet value
realMultiplet <- synthetic.mul %>% 
  select(gene, real.multiplet) %>% 
  distinct()

p2 <- synthetic.mul %>%
  #plot
  ggplot() +
  #synthetic multiplet values
  geom_rug(aes(value), size = 0.1) +
  facet_grid(gene ~ type, scales = "free_y") +
  #this just facilitates the histogram legend
  geom_line(
    aes(x = 0, y = 0, linetype = "Synthetic multiplet values  ")
  ) +
  #poisson distribution of individual synthetic multiplets
  geom_line(
    data = poissonDistSM,
    aes(pos, ind.dpois.norm, group = interaction(gene, type, value), linetype = "Distribution  "),
    size = 0.1, colour = "lightgrey"
  ) +
  #costs
  geom_line(
    data = entireCost,
    aes(dpois.x, cost.norm, linetype = "Costs  "), 
    colour = "#3366FF"
  ) +
  #real multiplet value
  geom_segment(
    data = realMultiplet,
    aes(
      x = real.multiplet, xend = real.multiplet, y = 0, yend = 1.05,
      linetype = "Real multiplet values  "
    ),
    size = 0.5, colour = "red"
  ) +
  #adds mean cost
  geom_text(
    data = realCost,
    aes(
      x = 0, y = 1.1, label = paste0("Mean cost: ", round(cost.real, digits = 2))
    ), colour = "gray13", hjust = 0, size = 3.5
  ) +
  theme_few() +
  labs(y = "Density", x = "CPM") +
  scale_y_continuous(
    breaks = seq(0, 1, 0.2), 
    sec.axis = sec_axis(~. * max.cost, name = "Cost")
  ) +
  scale_linetype_manual(values = c(1, 1, 2, 1)) +
  guides(linetype = guide_legend(
      title = "",
      override.aes = list(
        fill = rep("white", 4),
        colour = c("#3366FF", "lightgrey", "red", "black")
      )
  )) +
  theme(
    legend.position = "top",
    legend.key = element_blank(),
    legend.title = element_blank()
  )

p2
```

```{r, eval = TRUE}
p1 <- p1 +
  theme(
    axis.title.y = element_blank(),
    legend.position = "top",
    legend.margin = margin(rep(0, 4), unit = "pt"),
    legend.box.margin=margin(c(1, 0, -15, 0)),
    legend.box.spacing = unit(5, "pt"),
    plot.margin = unit(rep(0.1, 4), "lines"),
    legend.background = element_blank(),
    legend.key.size = unit(1/2, "cm"),
    plot.title = element_text(hjust = -0.2)
  ) +
  guides(colour = guide_legend(
    title = "Gene",
    title.position = "left",
    title.hjust = 0.5,
    ncol = 1
  )) +
  ggtitle("A)")

p2 <- p2 + theme(
    strip.text = element_text(size = 8),
    plot.title = element_text(hjust = -0.05)
  ) + 
  ggtitle("B)")

p <- p1 + p2 + plot_layout(ncol = 2, widths = c(1, 3))

ggsave(
  plot = p1,
  filename = '../figures/figure1.pdf',
  device = cairo_pdf,
  height = 180,
  width = 120,
  units = "mm"
)

ggsave(
  plot = p2,
  filename = '../figures/figure2.pdf',
  device = cairo_pdf,
  height = 180,
  width = 240,
  units = "mm"
)

ggsave(
  plot = p,
  filename = '../figures/figure.pdf',
  device = cairo_pdf,
  height = 180,
  width = 240,
  units = "mm"
)
```

```{r}
sessionInfo()
```

```{r, eval = FALSE}
synthetic.mul <- synthetic.mul %>%
  filter(str_detect(gene, "HCT116")) %>%
  mutate(type = parse_factor(
    type,
    levels = c("Fraction too low", "Fraction correct", "Fraction too high")
  ))

poissonDistSM <- synthetic.mul %>%
  mutate(pos = list(seq(0, max(value) + 200, 10))) %>%
  mutate(ind.dpois = map2(value, pos, ~dpois(.y, .x))) %>%
  unnest() %>%
  group_by(gene, type) %>%
  mutate(
    ind.dpois.norm = (ind.dpois - min(ind.dpois)) / (max(ind.dpois) - min(ind.dpois))
  )

#calculate dpois only for the real synthetic multiplet values to be able to 
#show the real mean cost per gene
realCost <- synthetic.mul %>%
  mutate(dpois.real = map2_dbl(real.multiplet, value, ~dpois(.x, .y, FALSE))) %>%
  group_by(gene, type) %>%
  summarize(mean.dpois = mean(dpois.real)) %>%
  ungroup() %>%
  mutate(mean.log = log10(mean.dpois)) %>%
  mutate(cost.real = if_else(is.infinite(mean.log), 323.0052, mean.log * - 1))

#calculate the entire cost space (blue line)
entireCost <- synthetic.mul %>%
  mutate(dpois.x = list(round(seq(0, max(value), 1)))) %>%
  unnest() %>%
  mutate(dpois = dpois(dpois.x, value)) %>%
  group_by(gene, type, dpois.x) %>%
  summarize(mean = mean(dpois)) %>%
  mutate(mean.log = log10(mean)) %>%
  mutate(cost = if_else(is.infinite(mean.log), 323.005, mean.log * - 1)) %>%
  ungroup() %>%
  mutate(cost.norm = (cost - min(cost)) / (max(cost) - min(cost)))

max.cost <- max(entireCost$cost)

#isolate the real multiplet value
realMultiplet <- synthetic.mul %>% 
  select(gene, real.multiplet) %>% 
  distinct()

synthetic.mul %>%
  #plot
  ggplot() +
  #synthetic multiplet values
  geom_rug(aes(value, colour = type), size = 0.1) +
  #facet_grid(gene ~ type, scales = "free_y") +
  #this just facilitates the histogram legend
  geom_line(
    aes(x = 0, y = 0, linetype = "Synthetic multiplet values  ")
  ) +
  #poisson distribution of individual synthetic multiplets
  geom_line(
    data = poissonDistSM,
    aes(pos, ind.dpois.norm, group = interaction(gene, type, value), colour = type, linetype = "Distribution  "),
    size = 0.1, colour = "lightgrey"
  ) +
  #costs
  geom_line(
    data = entireCost,
    aes(dpois.x, cost.norm, linetype = "Costs  "), 
    colour = "#3366FF"
  ) +
  #real multiplet value
  geom_segment(
    data = realMultiplet,
    aes(
      x = real.multiplet, xend = real.multiplet, y = 0, yend = 1.05,
      linetype = "Real multiplet values  "
    ),
    size = 0.5, colour = "red"
  ) +
  #adds mean cost
  geom_text(
    data = realCost,
    aes(
      x = 0, y = 1.1, label = paste0("Mean cost: ", round(cost.real, digits = 2))
    ), colour = "gray13", hjust = 0, size = 3.5
  ) +
  theme_few() +
  labs(y = "Density", x = "CPM") +
  scale_y_continuous(
    breaks = seq(0, 1, 0.2), 
    sec.axis = sec_axis(~. * max.cost, name = "Cost")
  ) +
  scale_linetype_manual(values = c(1, 1, 2, 1)) +
  guides(linetype = guide_legend(
      title = "",
      override.aes = list(
        fill = rep("white", 4),
        colour = c("#3366FF", "lightgrey", "red", "black")
      )
  )) +
  theme(
    legend.position = "top",
    legend.key = element_blank(),
    legend.title = element_blank()
  )
```

